services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    command: ["sh", "-c", "./wait-for-it.sh cityops_db:5432 --strict --timeout=60 -- ./start-dev.sh"]
    volumes:
        - .:/app
    env_file:
      - .env
    depends_on:
      cityops_db:
        condition: service_healthy

  cityops_db:
    container_name: database
    image: postgis/postgis
    platform: linux/amd64
    restart: always
    volumes:
      - cityops_db_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  cityops_db_data:
