[pytest]
DJANGO_SETTINGS_MODULE = cityops.settings
python_files = test_*.py *_tests.py
testpaths = apps
addopts = --cov --cov-config=.coveragerc --cov-report=xml:coverage.xml --cov-report=term-missing
