sonar.organization=cityopz
sonar.projectKey=cityopz_backend
sonar.projectName=cityopz_backend

sonar.sources=apps
sonar.tests=apps 

sonar.test.inclusions=**/tests/**/*.py,**/test_*.py,**/*_test.py
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/.venv/**,**/venv/**,**/static/**,**/media/**,**/htmlcov/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.exclusions=**/migrations/**,**/tests/**,**/admin.py,**/apps.py,**/manage.py,**/settings.py,**/urls.py,**/wsgi.py,**/asgi.py
