# Generated by Django 6.0.6 on 2026-06-29 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('IN_REPAIR', 'In Repair'), ('RESOLVED', 'Resolved')], max_length=20)),
                ('previous_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('IN_REPAIR', 'In Repair'), ('RESOLVED', 'Resolved')], max_length=20)),
                ('update_detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reports.report')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
