name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with: 
          fetch-depth: 0

      - name: Create env file
        run: |
          cp .env.example .env

      - name: Build containers
        run: | 
          docker compose -f docker-compose.yml build
        
      - name: Start database
        run: |
          docker compose -f docker-compose.yml up -d cityops_db

      - name: Wait for database 
        run: |
          until docker compose -f docker-compose.yml exec -T cityops_db sh -c 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"'; do 
            echo "Waiting for database..."
            sleep 2
          done 
      
      - name: Run backend tests with coverage
        run: |
          docker compose -f docker-compose.yml run --rm --user "(id -u):(id -g)" web pytest --cov=apps --cov-report=xml --cov-report=term-missing

      - name: Check coverage file
        run: |
          ls -la coverage.xml 

      - name: SonarQube Cloud Scan 
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Stop containers
        if: always()
        run: |
          docker compose -f docker-compose.yml down -v
